Skip @eaDir directories
I'm running on a Synology NAS and it creates some directories starting with `@` and `#` that are used for metadata and integrity info. This patch ignores those

```  File "/volume1/@appstore/python/lib/python2.7/site-packages/gmv/gmvault_db.py", line 137, in _init_sub_chats_dir
    raise Exception("Should get 2 elements in %s" % the_split)
Exception: Should get 2 elements in ['@eaDir']```